### ISSUE TITLE
Automate creation of docker build images

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/model_builder#2]
Need a process for automating building docker images with appropriate packages built by the meta build tool #1

**Comment by aidanheerdegen** [comment]
COSIMA are building containers for CI with ACCESS-OM3

https://github.com/COSIMA/access-om3-ci-images

**Comment by aidanheerdegen** [comment]
Related: This is a useful write-up of how "smart" caching can be used to auto-build container images when dependencies change

https://mmeendez8.github.io/2021/04/23/cache-docker.html

**Comment by aidanheerdegen** [comment]
Linked from article above, but goes into more detail:

https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

**Comment by aidanheerdegen** [comment]
@echus this method of installing only the dependencies breaks in the newest spack apparently
```
# Install dependencies separately for caching
RUN spack install --only dependencies access.nri.oasis3-mct
```
From [spack slack](https://spackpm.slack.com/archives/C5W7NKZJT/p1677338698445349):

> I used to use `spack install --only dependencies hpctoolkit` to install the dependencies and compile my own hpctoolkit. but since the latest spack has to use `spack add` before the installation, could you tell me how to `spack add` only dependencies for hpctoolkit?

[Solution appears to be](https://spackpm.slack.com/archives/C5W7NKZJT/p1677344047192479?thread_ts=1677338698.445349&cid=C5W7NKZJT):

> Why can't you just `spack add hpctoolkit` and then `spack install --only dependencies`? It should be the same as before

**Comment by aidanheerdegen** [comment]
I think this is taken care of by https://github.com/ACCESS-NRI/build-ci right @echus ?

In which case it can be closed.

**Comment by echus** [comment]
Yep, it is!
